# Generated by Django 5.2.5 on 2025-08-21 05:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_url_alter_useraddress_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='avatar'),
        ),
    ]
