# Generated by Django 5.2.5 on 2025-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_default', True)),
                fields=('user',),
                name='unique_default_address_per_user',
            ),
        ),
    ]
