# Generated by Django 5.2.5 on 2025-08-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_amount", models.IntegerField()),
                ("min_quantity", models.IntegerField()),
                ("goal_choice", models.CharField(max_length=10)),
                ("deadline", models.DateTimeField()),
                ("status", models.CharField(max_length=20)),
                ("banner", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="JoinedGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField()),
            ],
        ),
    ]
