# Generated by Django 5.2.5 on 2025-08-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="buyers",
        ),
        migrations.AlterField(
            model_name="group",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="min_amount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="min_quantity",
            field=models.IntegerField(null=True),
        ),
    ]
