# Generated by Django 5.2.5 on 2025-08-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_joinedgroup_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='group',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='goal_choice',
        ),
        migrations.RemoveField(
            model_name='group',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='group',
            name='min_quantity',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='group',
            name='status',
        ),
        migrations.AlterField(
            model_name='group',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='groups/banners/'),
        ),
    ]
