# Generated by Django 5.2.5 on 2025-08-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_joinedgroup_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='banner',
            field=models.ImageField(upload_to='groups/banners/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='min_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='min_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
