# Generated by Django 5.2.5 on 2025-08-19 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_created_at_remove_group_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='goal_choice',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='min_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='min_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
