# Generated by Django 5.2.5 on 2025-08-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='min_amount',
            new_name='min_goal',
        ),
        migrations.RemoveField(
            model_name='group',
            name='min_quantity',
        ),
    ]
