# Generated by Django 5.2.5 on 2025-08-29 09:39

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_created_at_alter_group_min_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='goal_choice',
            field=models.CharField(choices=[('quantity', '數量目標'), ('amount', '金額目標')], max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=django_fsm.FSMField(choices=[('準備中', '準備中'), ('進行中', '進行中'), ('已達標', '已達標'), ('已失敗', '已失敗'), ('已取消', '已取消')], default='準備中', max_length=50, protected=True),
        ),
    ]
