# Generated by Django 5.2.5 on 2025-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_created_at_alter_group_min_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
