# Generated by Django 5.2.5 on 2025-08-26 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_created_at_alter_group_min_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='current_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='joinedgroup',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='joinedgroup',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='joinedgroup',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='joinedgroup',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joinedgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['owner'], name='groups_grou_owner_i_11ab1b_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status'], name='groups_grou_status_952d41_idx'),
        ),
        migrations.AddIndex(
            model_name='joinedgroup',
            index=models.Index(fields=['buyer'], name='groups_join_buyer_i_11cec3_idx'),
        ),
        migrations.AddIndex(
            model_name='joinedgroup',
            index=models.Index(fields=['group'], name='groups_join_group_i_4603ed_idx'),
        ),
        migrations.AddIndex(
            model_name='joinedgroup',
            index=models.Index(fields=['status'], name='groups_join_status_d1de19_idx'),
        ),
        migrations.AddIndex(
            model_name='joinedgroup',
            index=models.Index(fields=['-created_at'], name='groups_join_created_69b722_idx'),
        ),
    ]
