# Generated by Django 5.2.5 on 2025-08-29 09:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_group_current_progress_group_total_alter_group_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
