# Generated by Django 5.2.5 on 2025-08-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "groups",
            "0009_group_current_progress_group_total_alter_group_owner_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="joinedgroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
