# Generated by Django 5.2.5 on 2025-09-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_alter_group_goal_choice_alter_group_status'),
        ('groups', '0009_group_current_progress_group_total_alter_group_owner_and_more'),
    ]

    operations = [
    ]
