# Generated by Django 5.2.5 on 2025-09-02 04:00

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_merge_20250902_0358'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', '準備中'), ('ongoing', '進行中'), ('reached', '已達標'), ('failed', '已失敗'), ('deleted', '已取消')], default='pending', max_length=50, protected=True),
        ),
    ]
