# Generated by Django 5.2.5 on 2025-08-29 09:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0010_joinedgroup_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
