# Generated by Django 5.2.5 on 2025-09-03 05:08

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0011_alter_group_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="goal_choice",
            field=models.CharField(
                choices=[("quantity", "數量目標"), ("amount", "金額目標")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "準備中"),
                    ("ongoing", "進行中"),
                    ("reached", "已達標"),
                    ("failed", "已失敗"),
                    ("deleted", "已取消"),
                ],
                default="pending",
                max_length=50,
                protected=True,
            ),
        ),
    ]
