# Generated by Django 5.2.6 on 2025-09-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0012_alter_group_goal_choice_alter_group_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinedgroup",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
