# Generated by Django 5.2.5 on 2025-08-26 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0008_alter_group_created_at_alter_group_min_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TWD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(default='pending', max_length=30)),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='groups.group'
                    ),
                ),
                (
                    'joined_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='groups.joinedgroup',
                    ),
                ),
            ],
        ),
    ]
