# Generated by Django 5.2.5 on 2025-08-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('pending', '待處理'),
                    ('paid', '已付款'),
                    ('failed', '付款失敗'),
                ],
                default='pending',
                max_length=30,
            ),
        ),
    ]
