# Generated by Django 5.2.5 on 2025-08-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_created_at_alter_group_min_goal'),
        ('orders', '0003_alter_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='joined_group',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to='groups.joinedgroup'
            ),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                (
                    'payment_status',
                    models.CharField(
                        choices=[
                            ('pending', '待付款'),
                            ('paid', '已付款'),
                            ('failed', '付款失敗'),
                        ],
                        default='pending',
                        max_length=30,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='orders.order'
                    ),
                ),
            ],
        ),
    ]
