# Generated by Django 5.2.5 on 2025-08-27 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_created_at_alter_group_min_goal'),
        ('orders', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='joined_group',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to='groups.joinedgroup'
            ),
        ),
    ]
