# Generated by Django 5.2.5 on 2025-08-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'orders',
            '0004_remove_order_payment_status_alter_order_joined_group_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(
                choices=[
                    ('pending', '待付款'),
                    ('processing', '待出貨'),
                    ('shipped', '已出貨'),
                    ('completed', '已完成'),
                ],
                default='pending',
                max_length=30,
            ),
        ),
    ]
