# Generated by Django 5.2.5 on 2025-08-29 06:50

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=django_fsm.FSMField(
                choices=[
                    ('pending', '待付款'),
                    ('processing', '待出貨'),
                    ('shipped', '已出貨'),
                    ('completed', '已完成'),
                ],
                default='pending',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=django_fsm.FSMField(
                choices=[
                    ('pending', '待付款'),
                    ('paid', '已付款'),
                    ('failed', '付款失敗'),
                ],
                default='pending',
                max_length=30,
            ),
        ),
    ]
