# Generated by Django 5.2.5 on 2025-08-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_joined_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='number',
        ),
    ]
