# Generated by Django 5.2.5 on 2025-08-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_order_number_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('processing', '待出貨'),
                    ('shipped', '已出貨'),
                    ('completed', '已完成'),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
