# Generated by Django 5.2.5 on 2025-08-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
