# Generated by Django 5.2.5 on 2025-08-16 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_usernotification_read_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotification",
            name="created_at",
        ),
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
