# Generated by Django 5.2.5 on 2025-08-20 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_joinedgroup_deleted_at'),
        ('notifications', '0004_remove_usernotification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='notifications',
                to='groups.group',
            ),
        ),
    ]
