# Generated by Django 5.2.5 on 2025-08-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_created_at_alter_group_min_goal'),
        ('notifications', '0005_notification_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notifications',
                to='groups.group',
            ),
        ),
    ]
