# Generated by Django 5.2.5 on 2025-08-15 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_joinedgroup_deleted_at'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedGroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('joined_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_group_products', to='groups.joinedgroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
