# Generated by Django 5.2.5 on 2025-08-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_joinedgroupproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(upload_to='groups/products'),
        ),
    ]
