# Generated by Django 5.2.5 on 2025-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedgroupproduct',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
