# Generated by Django 5.2.5 on 2025-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_joinedgroupproduct_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
