# Generated by Django 5.2.5 on 2025-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ImageField(null=True, upload_to='products/banners/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
